//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBlue.Business.Enterprise.InvoiceGeneration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/SiteBlue.DocumentGeneration.Invoices")]
    [System.SerializableAttribute()]
    public partial class Invoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DBAIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiagnosticsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranchiseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FranchiseTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasAcceptSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasAuthSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEstimateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMemberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SiteBlue.Business.Enterprise.InvoiceGeneration.InvoiceLine[] LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SiteBlue.Business.Enterprise.InvoiceGeneration.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecommendationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SubTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Warranty1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Warranty1LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Warranty2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Warranty2LengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType {
            get {
                return this.BusinessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTypeField, value) != true)) {
                    this.BusinessTypeField = value;
                    this.RaisePropertyChanged("BusinessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallReason {
            get {
                return this.CallReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.CallReasonField, value) != true)) {
                    this.CallReasonField = value;
                    this.RaisePropertyChanged("CallReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Completed {
            get {
                return this.CompletedField;
            }
            set {
                if ((this.CompletedField.Equals(value) != true)) {
                    this.CompletedField = value;
                    this.RaisePropertyChanged("Completed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DBAId {
            get {
                return this.DBAIdField;
            }
            set {
                if ((this.DBAIdField.Equals(value) != true)) {
                    this.DBAIdField = value;
                    this.RaisePropertyChanged("DBAId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diagnostics {
            get {
                return this.DiagnosticsField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosticsField, value) != true)) {
                    this.DiagnosticsField = value;
                    this.RaisePropertyChanged("Diagnostics");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranchiseId {
            get {
                return this.FranchiseIdField;
            }
            set {
                if ((this.FranchiseIdField.Equals(value) != true)) {
                    this.FranchiseIdField = value;
                    this.RaisePropertyChanged("FranchiseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FranchiseTypeID {
            get {
                return this.FranchiseTypeIDField;
            }
            set {
                if ((this.FranchiseTypeIDField.Equals(value) != true)) {
                    this.FranchiseTypeIDField = value;
                    this.RaisePropertyChanged("FranchiseTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCity {
            get {
                return this.FromCityField;
            }
            set {
                if ((object.ReferenceEquals(this.FromCityField, value) != true)) {
                    this.FromCityField = value;
                    this.RaisePropertyChanged("FromCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromName {
            get {
                return this.FromNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromNameField, value) != true)) {
                    this.FromNameField = value;
                    this.RaisePropertyChanged("FromName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhone {
            get {
                return this.FromPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneField, value) != true)) {
                    this.FromPhoneField = value;
                    this.RaisePropertyChanged("FromPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromState {
            get {
                return this.FromStateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromStateField, value) != true)) {
                    this.FromStateField = value;
                    this.RaisePropertyChanged("FromState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromZip {
            get {
                return this.FromZipField;
            }
            set {
                if ((object.ReferenceEquals(this.FromZipField, value) != true)) {
                    this.FromZipField = value;
                    this.RaisePropertyChanged("FromZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAcceptSignature {
            get {
                return this.HasAcceptSignatureField;
            }
            set {
                if ((this.HasAcceptSignatureField.Equals(value) != true)) {
                    this.HasAcceptSignatureField = value;
                    this.RaisePropertyChanged("HasAcceptSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAuthSignature {
            get {
                return this.HasAuthSignatureField;
            }
            set {
                if ((this.HasAuthSignatureField.Equals(value) != true)) {
                    this.HasAuthSignatureField = value;
                    this.RaisePropertyChanged("HasAuthSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEstimate {
            get {
                return this.IsEstimateField;
            }
            set {
                if ((this.IsEstimateField.Equals(value) != true)) {
                    this.IsEstimateField = value;
                    this.RaisePropertyChanged("IsEstimate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMember {
            get {
                return this.IsMemberField;
            }
            set {
                if ((this.IsMemberField.Equals(value) != true)) {
                    this.IsMemberField = value;
                    this.RaisePropertyChanged("IsMember");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobID {
            get {
                return this.JobIDField;
            }
            set {
                if ((this.JobIDField.Equals(value) != true)) {
                    this.JobIDField = value;
                    this.RaisePropertyChanged("JobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseNumber {
            get {
                return this.LicenseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseNumberField, value) != true)) {
                    this.LicenseNumberField = value;
                    this.RaisePropertyChanged("LicenseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SiteBlue.Business.Enterprise.InvoiceGeneration.InvoiceLine[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationAddress {
            get {
                return this.LocationAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationAddressField, value) != true)) {
                    this.LocationAddressField = value;
                    this.RaisePropertyChanged("LocationAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCity {
            get {
                return this.LocationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCityField, value) != true)) {
                    this.LocationCityField = value;
                    this.RaisePropertyChanged("LocationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationPhone {
            get {
                return this.LocationPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationPhoneField, value) != true)) {
                    this.LocationPhoneField = value;
                    this.RaisePropertyChanged("LocationPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationState {
            get {
                return this.LocationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationStateField, value) != true)) {
                    this.LocationStateField = value;
                    this.RaisePropertyChanged("LocationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationZip {
            get {
                return this.LocationZipField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationZipField, value) != true)) {
                    this.LocationZipField = value;
                    this.RaisePropertyChanged("LocationZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SiteBlue.Business.Enterprise.InvoiceGeneration.Payment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recommendations {
            get {
                return this.RecommendationsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecommendationsField, value) != true)) {
                    this.RecommendationsField = value;
                    this.RaisePropertyChanged("Recommendations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SubTotal {
            get {
                return this.SubTotalField;
            }
            set {
                if ((this.SubTotalField.Equals(value) != true)) {
                    this.SubTotalField = value;
                    this.RaisePropertyChanged("SubTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TaxAmount {
            get {
                return this.TaxAmountField;
            }
            set {
                if ((this.TaxAmountField.Equals(value) != true)) {
                    this.TaxAmountField = value;
                    this.RaisePropertyChanged("TaxAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Technician {
            get {
                return this.TechnicianField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicianField, value) != true)) {
                    this.TechnicianField = value;
                    this.RaisePropertyChanged("Technician");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToAddress {
            get {
                return this.ToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToAddressField, value) != true)) {
                    this.ToAddressField = value;
                    this.RaisePropertyChanged("ToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCity {
            get {
                return this.ToCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCityField, value) != true)) {
                    this.ToCityField = value;
                    this.RaisePropertyChanged("ToCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToEmail {
            get {
                return this.ToEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ToEmailField, value) != true)) {
                    this.ToEmailField = value;
                    this.RaisePropertyChanged("ToEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToName {
            get {
                return this.ToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ToNameField, value) != true)) {
                    this.ToNameField = value;
                    this.RaisePropertyChanged("ToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhone {
            get {
                return this.ToPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneField, value) != true)) {
                    this.ToPhoneField = value;
                    this.RaisePropertyChanged("ToPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToState {
            get {
                return this.ToStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ToStateField, value) != true)) {
                    this.ToStateField = value;
                    this.RaisePropertyChanged("ToState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToZip {
            get {
                return this.ToZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ToZipField, value) != true)) {
                    this.ToZipField = value;
                    this.RaisePropertyChanged("ToZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty1 {
            get {
                return this.Warranty1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Warranty1Field, value) != true)) {
                    this.Warranty1Field = value;
                    this.RaisePropertyChanged("Warranty1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty1Length {
            get {
                return this.Warranty1LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.Warranty1LengthField, value) != true)) {
                    this.Warranty1LengthField = value;
                    this.RaisePropertyChanged("Warranty1Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty2 {
            get {
                return this.Warranty2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Warranty2Field, value) != true)) {
                    this.Warranty2Field = value;
                    this.RaisePropertyChanged("Warranty2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warranty2Length {
            get {
                return this.Warranty2LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.Warranty2LengthField, value) != true)) {
                    this.Warranty2LengthField = value;
                    this.RaisePropertyChanged("Warranty2Length");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceLine", Namespace="http://schemas.datacontract.org/2004/07/SiteBlue.DocumentGeneration.Invoices")]
    [System.SerializableAttribute()]
    public partial class InvoiceLine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExtendedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExtendedPrice {
            get {
                return this.ExtendedPriceField;
            }
            set {
                if ((this.ExtendedPriceField.Equals(value) != true)) {
                    this.ExtendedPriceField = value;
                    this.RaisePropertyChanged("ExtendedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tax {
            get {
                return this.TaxField;
            }
            set {
                if ((this.TaxField.Equals(value) != true)) {
                    this.TaxField = value;
                    this.RaisePropertyChanged("Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/SiteBlue.DocumentGeneration.Invoices")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentType {
            get {
                return this.PaymentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTypeField, value) != true)) {
                    this.PaymentTypeField = value;
                    this.RaisePropertyChanged("PaymentType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Enterprise.InvoiceGeneration.IGenerateInvoices")]
    public interface IGenerateInvoices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateInvoices/Render", ReplyAction="http://tempuri.org/IGenerateInvoices/RenderResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult Render(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, byte[][] docsToAppend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateInvoices/RenderHtml", ReplyAction="http://tempuri.org/IGenerateInvoices/RenderHtmlResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderHtml(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateInvoices/RenderCustom", ReplyAction="http://tempuri.org/IGenerateInvoices/RenderCustomResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderCustom(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, string templatePath, byte[][] docsToAppend);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateInvoices/RenderHtmlCustom", ReplyAction="http://tempuri.org/IGenerateInvoices/RenderHtmlCustomResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderHtmlCustom(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, string templatePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerateInvoicesChannel : SiteBlue.Business.Enterprise.InvoiceGeneration.IGenerateInvoices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateInvoicesClient : System.ServiceModel.ClientBase<SiteBlue.Business.Enterprise.InvoiceGeneration.IGenerateInvoices>, SiteBlue.Business.Enterprise.InvoiceGeneration.IGenerateInvoices {
        
        public GenerateInvoicesClient() {
        }
        
        public GenerateInvoicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerateInvoicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateInvoicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateInvoicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult Render(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, byte[][] docsToAppend) {
            return base.Channel.Render(invoice, docsToAppend);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderHtml(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice) {
            return base.Channel.RenderHtml(invoice);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderCustom(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, string templatePath, byte[][] docsToAppend) {
            return base.Channel.RenderCustom(invoice, templatePath, docsToAppend);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderHtmlCustom(SiteBlue.Business.Enterprise.InvoiceGeneration.Invoice invoice, string templatePath) {
            return base.Channel.RenderHtmlCustom(invoice, templatePath);
        }
    }
}
