//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBlue.Core.Enterprise.DocumentGeneration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RenderResult", Namespace="http://schemas.datacontract.org/2004/07/SiteBlue.DocumentGeneration")]
    [System.SerializableAttribute()]
    public partial class RenderResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Enterprise.DocumentGeneration.IRenderDocuments")]
    public interface IRenderDocuments {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenderDocuments/PDFFromHtml", ReplyAction="http://tempuri.org/IRenderDocuments/PDFFromHtmlResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult PDFFromHtml(string html);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRenderDocuments/PDFFromUrl", ReplyAction="http://tempuri.org/IRenderDocuments/PDFFromUrlResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult PDFFromUrl(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRenderDocumentsChannel : SiteBlue.Core.Enterprise.DocumentGeneration.IRenderDocuments, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RenderDocumentsClient : System.ServiceModel.ClientBase<SiteBlue.Core.Enterprise.DocumentGeneration.IRenderDocuments>, SiteBlue.Core.Enterprise.DocumentGeneration.IRenderDocuments {
        
        public RenderDocumentsClient() {
        }
        
        public RenderDocumentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RenderDocumentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenderDocumentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RenderDocumentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult PDFFromHtml(string html) {
            return base.Channel.PDFFromHtml(html);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult PDFFromUrl(string url) {
            return base.Channel.PDFFromUrl(url);
        }
    }
}
