//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("IncomingCallsModel", "FK_StasticTracks_EndCallOptions", "EndCallOption", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SiteBlue.Data.EndCallOption), "StatisticTrack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SiteBlue.Data.StatisticTrack), true)]
[assembly: EdmRelationshipAttribute("IncomingCallsModel", "FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SiteBlue.Data.LookupScript), "Tbl_scriptToFranchiseID", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SiteBlue.Data.Tbl_scriptToFranchiseID), true)]

#endregion

namespace SiteBlue.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IncomingCallsQAEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IncomingCallsQAEntities object using the connection string found in the 'IncomingCallsQAEntities' section of the application configuration file.
        /// </summary>
        public IncomingCallsQAEntities() : base("name=IncomingCallsQAEntities", "IncomingCallsQAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IncomingCallsQAEntities object.
        /// </summary>
        public IncomingCallsQAEntities(string connectionString) : base(connectionString, "IncomingCallsQAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IncomingCallsQAEntities object.
        /// </summary>
        public IncomingCallsQAEntities(EntityConnection connection) : base(connection, "IncomingCallsQAEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LookupScript> LookupScripts
        {
            get
            {
                if ((_LookupScripts == null))
                {
                    _LookupScripts = base.CreateObjectSet<LookupScript>("LookupScripts");
                }
                return _LookupScripts;
            }
        }
        private ObjectSet<LookupScript> _LookupScripts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EndCallOption> EndCallOptions
        {
            get
            {
                if ((_EndCallOptions == null))
                {
                    _EndCallOptions = base.CreateObjectSet<EndCallOption>("EndCallOptions");
                }
                return _EndCallOptions;
            }
        }
        private ObjectSet<EndCallOption> _EndCallOptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StatisticTrack> StatisticTracks
        {
            get
            {
                if ((_StatisticTracks == null))
                {
                    _StatisticTracks = base.CreateObjectSet<StatisticTrack>("StatisticTracks");
                }
                return _StatisticTracks;
            }
        }
        private ObjectSet<StatisticTrack> _StatisticTracks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_scriptToFranchiseID> Tbl_scriptToFranchiseID
        {
            get
            {
                if ((_Tbl_scriptToFranchiseID == null))
                {
                    _Tbl_scriptToFranchiseID = base.CreateObjectSet<Tbl_scriptToFranchiseID>("Tbl_scriptToFranchiseID");
                }
                return _Tbl_scriptToFranchiseID;
            }
        }
        private ObjectSet<Tbl_scriptToFranchiseID> _Tbl_scriptToFranchiseID;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VADM_CallStats> VADM_CallStats
        {
            get
            {
                if ((_VADM_CallStats == null))
                {
                    _VADM_CallStats = base.CreateObjectSet<VADM_CallStats>("VADM_CallStats");
                }
                return _VADM_CallStats;
            }
        }
        private ObjectSet<VADM_CallStats> _VADM_CallStats;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LookupScripts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLookupScripts(LookupScript lookupScript)
        {
            base.AddObject("LookupScripts", lookupScript);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EndCallOptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndCallOptions(EndCallOption endCallOption)
        {
            base.AddObject("EndCallOptions", endCallOption);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StatisticTracks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStatisticTracks(StatisticTrack statisticTrack)
        {
            base.AddObject("StatisticTracks", statisticTrack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_scriptToFranchiseID EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_scriptToFranchiseID(Tbl_scriptToFranchiseID tbl_scriptToFranchiseID)
        {
            base.AddObject("Tbl_scriptToFranchiseID", tbl_scriptToFranchiseID);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VADM_CallStats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVADM_CallStats(VADM_CallStats vADM_CallStats)
        {
            base.AddObject("VADM_CallStats", vADM_CallStats);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<CallAnsweringScripts> CallAnsweringScript()
        {
            return base.ExecuteFunction<CallAnsweringScripts>("CallAnsweringScript");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IncomingCallsModel", Name="EndCallOption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EndCallOption : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EndCallOption object.
        /// </summary>
        /// <param name="optionId">Initial value of the OptionId property.</param>
        /// <param name="optionName">Initial value of the OptionName property.</param>
        public static EndCallOption CreateEndCallOption(global::System.Int32 optionId, global::System.String optionName)
        {
            EndCallOption endCallOption = new EndCallOption();
            endCallOption.OptionId = optionId;
            endCallOption.OptionName = optionName;
            return endCallOption;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OptionId
        {
            get
            {
                return _OptionId;
            }
            set
            {
                if (_OptionId != value)
                {
                    OnOptionIdChanging(value);
                    ReportPropertyChanging("OptionId");
                    _OptionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OptionId");
                    OnOptionIdChanged();
                }
            }
        }
        private global::System.Int32 _OptionId;
        partial void OnOptionIdChanging(global::System.Int32 value);
        partial void OnOptionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OptionName
        {
            get
            {
                return _OptionName;
            }
            set
            {
                OnOptionNameChanging(value);
                ReportPropertyChanging("OptionName");
                _OptionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OptionName");
                OnOptionNameChanged();
            }
        }
        private global::System.String _OptionName;
        partial void OnOptionNameChanging(global::System.String value);
        partial void OnOptionNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IncomingCallsModel", "FK_StasticTracks_EndCallOptions", "StatisticTrack")]
        public EntityCollection<StatisticTrack> StatisticTracks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StatisticTrack>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "StatisticTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StatisticTrack>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "StatisticTrack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IncomingCallsModel", Name="LookupScript")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LookupScript : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LookupScript object.
        /// </summary>
        /// <param name="lookupId">Initial value of the LookupId property.</param>
        /// <param name="lookupPhoneNr">Initial value of the LookupPhoneNr property.</param>
        /// <param name="connectusCode">Initial value of the ConnectusCode property.</param>
        /// <param name="callScript">Initial value of the CallScript property.</param>
        /// <param name="virtualPhoneNumber">Initial value of the VirtualPhoneNumber property.</param>
        public static LookupScript CreateLookupScript(global::System.Int32 lookupId, global::System.String lookupPhoneNr, global::System.String connectusCode, global::System.String callScript, global::System.Boolean virtualPhoneNumber)
        {
            LookupScript lookupScript = new LookupScript();
            lookupScript.LookupId = lookupId;
            lookupScript.LookupPhoneNr = lookupPhoneNr;
            lookupScript.ConnectusCode = connectusCode;
            lookupScript.CallScript = callScript;
            lookupScript.VirtualPhoneNumber = virtualPhoneNumber;
            return lookupScript;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LookupId
        {
            get
            {
                return _LookupId;
            }
            set
            {
                if (_LookupId != value)
                {
                    OnLookupIdChanging(value);
                    ReportPropertyChanging("LookupId");
                    _LookupId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LookupId");
                    OnLookupIdChanged();
                }
            }
        }
        private global::System.Int32 _LookupId;
        partial void OnLookupIdChanging(global::System.Int32 value);
        partial void OnLookupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LookupPhoneNr
        {
            get
            {
                return _LookupPhoneNr;
            }
            set
            {
                OnLookupPhoneNrChanging(value);
                ReportPropertyChanging("LookupPhoneNr");
                _LookupPhoneNr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LookupPhoneNr");
                OnLookupPhoneNrChanged();
            }
        }
        private global::System.String _LookupPhoneNr;
        partial void OnLookupPhoneNrChanging(global::System.String value);
        partial void OnLookupPhoneNrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectusCode
        {
            get
            {
                return _ConnectusCode;
            }
            set
            {
                OnConnectusCodeChanging(value);
                ReportPropertyChanging("ConnectusCode");
                _ConnectusCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectusCode");
                OnConnectusCodeChanged();
            }
        }
        private global::System.String _ConnectusCode;
        partial void OnConnectusCodeChanging(global::System.String value);
        partial void OnConnectusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CallScript
        {
            get
            {
                return _CallScript;
            }
            set
            {
                OnCallScriptChanging(value);
                ReportPropertyChanging("CallScript");
                _CallScript = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CallScript");
                OnCallScriptChanged();
            }
        }
        private global::System.String _CallScript;
        partial void OnCallScriptChanging(global::System.String value);
        partial void OnCallScriptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String XMLCode
        {
            get
            {
                return _XMLCode;
            }
            set
            {
                OnXMLCodeChanging(value);
                ReportPropertyChanging("XMLCode");
                _XMLCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("XMLCode");
                OnXMLCodeChanged();
            }
        }
        private global::System.String _XMLCode;
        partial void OnXMLCodeChanging(global::System.String value);
        partial void OnXMLCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean VirtualPhoneNumber
        {
            get
            {
                return _VirtualPhoneNumber;
            }
            set
            {
                OnVirtualPhoneNumberChanging(value);
                ReportPropertyChanging("VirtualPhoneNumber");
                _VirtualPhoneNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VirtualPhoneNumber");
                OnVirtualPhoneNumberChanged();
            }
        }
        private global::System.Boolean _VirtualPhoneNumber;
        partial void OnVirtualPhoneNumberChanging(global::System.Boolean value);
        partial void OnVirtualPhoneNumberChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IncomingCallsModel", "FK_Tbl_scriptToFranchiseID_LookupScript", "Tbl_scriptToFranchiseID")]
        public EntityCollection<Tbl_scriptToFranchiseID> Tbl_scriptToFranchiseID
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tbl_scriptToFranchiseID>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "Tbl_scriptToFranchiseID");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tbl_scriptToFranchiseID>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "Tbl_scriptToFranchiseID", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IncomingCallsModel", Name="StatisticTrack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StatisticTrack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StatisticTrack object.
        /// </summary>
        /// <param name="trackId">Initial value of the TrackId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="calledNumber">Initial value of the CalledNumber property.</param>
        /// <param name="dialedNumber">Initial value of the DialedNumber property.</param>
        public static StatisticTrack CreateStatisticTrack(global::System.Int32 trackId, global::System.Guid userId, global::System.DateTime startDate, global::System.String calledNumber, global::System.String dialedNumber)
        {
            StatisticTrack statisticTrack = new StatisticTrack();
            statisticTrack.TrackId = trackId;
            statisticTrack.UserId = userId;
            statisticTrack.StartDate = startDate;
            statisticTrack.CalledNumber = calledNumber;
            statisticTrack.DialedNumber = dialedNumber;
            return statisticTrack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrackId
        {
            get
            {
                return _TrackId;
            }
            set
            {
                if (_TrackId != value)
                {
                    OnTrackIdChanging(value);
                    ReportPropertyChanging("TrackId");
                    _TrackId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrackId");
                    OnTrackIdChanged();
                }
            }
        }
        private global::System.Int32 _TrackId;
        partial void OnTrackIdChanging(global::System.Int32 value);
        partial void OnTrackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CalledNumber
        {
            get
            {
                return _CalledNumber;
            }
            set
            {
                OnCalledNumberChanging(value);
                ReportPropertyChanging("CalledNumber");
                _CalledNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CalledNumber");
                OnCalledNumberChanged();
            }
        }
        private global::System.String _CalledNumber;
        partial void OnCalledNumberChanging(global::System.String value);
        partial void OnCalledNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DialedNumber
        {
            get
            {
                return _DialedNumber;
            }
            set
            {
                OnDialedNumberChanging(value);
                ReportPropertyChanging("DialedNumber");
                _DialedNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DialedNumber");
                OnDialedNumberChanged();
            }
        }
        private global::System.String _DialedNumber;
        partial void OnDialedNumberChanging(global::System.String value);
        partial void OnDialedNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Duration;
        partial void OnDurationChanging(Nullable<global::System.TimeSpan> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OptionId
        {
            get
            {
                return _OptionId;
            }
            set
            {
                OnOptionIdChanging(value);
                ReportPropertyChanging("OptionId");
                _OptionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OptionId");
                OnOptionIdChanged();
            }
        }
        private Nullable<global::System.Int32> _OptionId;
        partial void OnOptionIdChanging(Nullable<global::System.Int32> value);
        partial void OnOptionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jobid
        {
            get
            {
                return _Jobid;
            }
            set
            {
                OnJobidChanging(value);
                ReportPropertyChanging("Jobid");
                _Jobid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jobid");
                OnJobidChanged();
            }
        }
        private Nullable<global::System.Int32> _Jobid;
        partial void OnJobidChanging(Nullable<global::System.Int32> value);
        partial void OnJobidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IncomingCallsModel", "FK_StasticTracks_EndCallOptions", "EndCallOption")]
        public EndCallOption EndCallOption
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EndCallOption>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "EndCallOption").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EndCallOption>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "EndCallOption").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EndCallOption> EndCallOptionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EndCallOption>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "EndCallOption");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EndCallOption>("IncomingCallsModel.FK_StasticTracks_EndCallOptions", "EndCallOption", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IncomingCallsModel", Name="Tbl_scriptToFranchiseID")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_scriptToFranchiseID : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_scriptToFranchiseID object.
        /// </summary>
        /// <param name="franchiseScriptID">Initial value of the FranchiseScriptID property.</param>
        /// <param name="scriptID">Initial value of the ScriptID property.</param>
        /// <param name="franchiseID">Initial value of the FranchiseID property.</param>
        public static Tbl_scriptToFranchiseID CreateTbl_scriptToFranchiseID(global::System.Int32 franchiseScriptID, global::System.Int32 scriptID, global::System.Int32 franchiseID)
        {
            Tbl_scriptToFranchiseID tbl_scriptToFranchiseID = new Tbl_scriptToFranchiseID();
            tbl_scriptToFranchiseID.FranchiseScriptID = franchiseScriptID;
            tbl_scriptToFranchiseID.ScriptID = scriptID;
            tbl_scriptToFranchiseID.FranchiseID = franchiseID;
            return tbl_scriptToFranchiseID;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FranchiseScriptID
        {
            get
            {
                return _FranchiseScriptID;
            }
            set
            {
                if (_FranchiseScriptID != value)
                {
                    OnFranchiseScriptIDChanging(value);
                    ReportPropertyChanging("FranchiseScriptID");
                    _FranchiseScriptID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FranchiseScriptID");
                    OnFranchiseScriptIDChanged();
                }
            }
        }
        private global::System.Int32 _FranchiseScriptID;
        partial void OnFranchiseScriptIDChanging(global::System.Int32 value);
        partial void OnFranchiseScriptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScriptID
        {
            get
            {
                return _ScriptID;
            }
            set
            {
                OnScriptIDChanging(value);
                ReportPropertyChanging("ScriptID");
                _ScriptID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScriptID");
                OnScriptIDChanged();
            }
        }
        private global::System.Int32 _ScriptID;
        partial void OnScriptIDChanging(global::System.Int32 value);
        partial void OnScriptIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FranchiseID
        {
            get
            {
                return _FranchiseID;
            }
            set
            {
                OnFranchiseIDChanging(value);
                ReportPropertyChanging("FranchiseID");
                _FranchiseID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FranchiseID");
                OnFranchiseIDChanged();
            }
        }
        private global::System.Int32 _FranchiseID;
        partial void OnFranchiseIDChanging(global::System.Int32 value);
        partial void OnFranchiseIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("IncomingCallsModel", "FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript")]
        public LookupScript LookupScript
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LookupScript>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LookupScript>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LookupScript> LookupScriptReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LookupScript>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LookupScript>("IncomingCallsModel.FK_Tbl_scriptToFranchiseID_LookupScript", "LookupScript", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IncomingCallsModel", Name="VADM_CallStats")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VADM_CallStats : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VADM_CallStats object.
        /// </summary>
        /// <param name="seqnr">Initial value of the seqnr property.</param>
        /// <param name="calltime">Initial value of the calltime property.</param>
        /// <param name="calledNumber">Initial value of the CalledNumber property.</param>
        /// <param name="callerid">Initial value of the callerid property.</param>
        public static VADM_CallStats CreateVADM_CallStats(global::System.Int32 seqnr, global::System.DateTime calltime, global::System.String calledNumber, global::System.String callerid)
        {
            VADM_CallStats vADM_CallStats = new VADM_CallStats();
            vADM_CallStats.seqnr = seqnr;
            vADM_CallStats.calltime = calltime;
            vADM_CallStats.CalledNumber = calledNumber;
            vADM_CallStats.callerid = callerid;
            return vADM_CallStats;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 seqnr
        {
            get
            {
                return _seqnr;
            }
            set
            {
                if (_seqnr != value)
                {
                    OnseqnrChanging(value);
                    ReportPropertyChanging("seqnr");
                    _seqnr = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("seqnr");
                    OnseqnrChanged();
                }
            }
        }
        private global::System.Int32 _seqnr;
        partial void OnseqnrChanging(global::System.Int32 value);
        partial void OnseqnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime calltime
        {
            get
            {
                return _calltime;
            }
            set
            {
                if (_calltime != value)
                {
                    OncalltimeChanging(value);
                    ReportPropertyChanging("calltime");
                    _calltime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("calltime");
                    OncalltimeChanged();
                }
            }
        }
        private global::System.DateTime _calltime;
        partial void OncalltimeChanging(global::System.DateTime value);
        partial void OncalltimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CalledNumber
        {
            get
            {
                return _CalledNumber;
            }
            set
            {
                if (_CalledNumber != value)
                {
                    OnCalledNumberChanging(value);
                    ReportPropertyChanging("CalledNumber");
                    _CalledNumber = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CalledNumber");
                    OnCalledNumberChanged();
                }
            }
        }
        private global::System.String _CalledNumber;
        partial void OnCalledNumberChanging(global::System.String value);
        partial void OnCalledNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CalledDescription
        {
            get
            {
                return _CalledDescription;
            }
            set
            {
                OnCalledDescriptionChanging(value);
                ReportPropertyChanging("CalledDescription");
                _CalledDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CalledDescription");
                OnCalledDescriptionChanged();
            }
        }
        private global::System.String _CalledDescription;
        partial void OnCalledDescriptionChanging(global::System.String value);
        partial void OnCalledDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String callerid
        {
            get
            {
                return _callerid;
            }
            set
            {
                if (_callerid != value)
                {
                    OncalleridChanging(value);
                    ReportPropertyChanging("callerid");
                    _callerid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("callerid");
                    OncalleridChanged();
                }
            }
        }
        private global::System.String _callerid;
        partial void OncalleridChanging(global::System.String value);
        partial void OncalleridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Duration;
        partial void OnDurationChanging(Nullable<global::System.TimeSpan> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Jobid
        {
            get
            {
                return _Jobid;
            }
            set
            {
                OnJobidChanging(value);
                ReportPropertyChanging("Jobid");
                _Jobid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jobid");
                OnJobidChanged();
            }
        }
        private Nullable<global::System.Int32> _Jobid;
        partial void OnJobidChanging(Nullable<global::System.Int32> value);
        partial void OnJobidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OptionName
        {
            get
            {
                return _OptionName;
            }
            set
            {
                OnOptionNameChanging(value);
                ReportPropertyChanging("OptionName");
                _OptionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OptionName");
                OnOptionNameChanged();
            }
        }
        private global::System.String _OptionName;
        partial void OnOptionNameChanging(global::System.String value);
        partial void OnOptionNameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="IncomingCallsModel", Name="CallAnsweringScripts")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CallAnsweringScripts : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CallAnsweringScripts object.
        /// </summary>
        /// <param name="franchiseTypeId">Initial value of the FranchiseTypeId property.</param>
        /// <param name="franchiseId">Initial value of the FranchiseId property.</param>
        /// <param name="connectUsCode">Initial value of the ConnectUsCode property.</param>
        /// <param name="callScript">Initial value of the CallScript property.</param>
        public static CallAnsweringScripts CreateCallAnsweringScripts(global::System.Int32 franchiseTypeId, global::System.Int32 franchiseId, global::System.String connectUsCode, global::System.String callScript)
        {
            CallAnsweringScripts callAnsweringScripts = new CallAnsweringScripts();
            callAnsweringScripts.FranchiseTypeId = franchiseTypeId;
            callAnsweringScripts.FranchiseId = franchiseId;
            callAnsweringScripts.ConnectUsCode = connectUsCode;
            callAnsweringScripts.CallScript = callScript;
            return callAnsweringScripts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FranchiseTypeId
        {
            get
            {
                return _FranchiseTypeId;
            }
            set
            {
                OnFranchiseTypeIdChanging(value);
                ReportPropertyChanging("FranchiseTypeId");
                _FranchiseTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FranchiseTypeId");
                OnFranchiseTypeIdChanged();
            }
        }
        private global::System.Int32 _FranchiseTypeId;
        partial void OnFranchiseTypeIdChanging(global::System.Int32 value);
        partial void OnFranchiseTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FranchiseId
        {
            get
            {
                return _FranchiseId;
            }
            set
            {
                OnFranchiseIdChanging(value);
                ReportPropertyChanging("FranchiseId");
                _FranchiseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FranchiseId");
                OnFranchiseIdChanged();
            }
        }
        private global::System.Int32 _FranchiseId;
        partial void OnFranchiseIdChanging(global::System.Int32 value);
        partial void OnFranchiseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectUsCode
        {
            get
            {
                return _ConnectUsCode;
            }
            set
            {
                OnConnectUsCodeChanging(value);
                ReportPropertyChanging("ConnectUsCode");
                _ConnectUsCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectUsCode");
                OnConnectUsCodeChanged();
            }
        }
        private global::System.String _ConnectUsCode;
        partial void OnConnectUsCodeChanging(global::System.String value);
        partial void OnConnectUsCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CallScript
        {
            get
            {
                return _CallScript;
            }
            set
            {
                OnCallScriptChanging(value);
                ReportPropertyChanging("CallScript");
                _CallScript = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CallScript");
                OnCallScriptChanged();
            }
        }
        private global::System.String _CallScript;
        partial void OnCallScriptChanging(global::System.String value);
        partial void OnCallScriptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FranchiseNumber
        {
            get
            {
                return _FranchiseNumber;
            }
            set
            {
                OnFranchiseNumberChanging(value);
                ReportPropertyChanging("FranchiseNumber");
                _FranchiseNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FranchiseNumber");
                OnFranchiseNumberChanged();
            }
        }
        private global::System.String _FranchiseNumber;
        partial void OnFranchiseNumberChanging(global::System.String value);
        partial void OnFranchiseNumberChanged();

        #endregion
    }

    #endregion
    
}
