//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBlue.Business.Enterprise.TechnicianBioGeneration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bio", Namespace="http://schemas.datacontract.org/2004/07/SiteBlue.DocumentGeneration.TechBios")]
    [System.SerializableAttribute()]
    public partial class Bio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BackgroundCheckCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFranchiseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastDrugTestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TechIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BackgroundCheckCompleted {
            get {
                return this.BackgroundCheckCompletedField;
            }
            set {
                if ((this.BackgroundCheckCompletedField.Equals(value) != true)) {
                    this.BackgroundCheckCompletedField = value;
                    this.RaisePropertyChanged("BackgroundCheckCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFranchise {
            get {
                return this.IsFranchiseField;
            }
            set {
                if ((this.IsFranchiseField.Equals(value) != true)) {
                    this.IsFranchiseField = value;
                    this.RaisePropertyChanged("IsFranchise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastDrugTest {
            get {
                return this.LastDrugTestField;
            }
            set {
                if ((this.LastDrugTestField.Equals(value) != true)) {
                    this.LastDrugTestField = value;
                    this.RaisePropertyChanged("LastDrugTest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TechId {
            get {
                return this.TechIdField;
            }
            set {
                if ((this.TechIdField.Equals(value) != true)) {
                    this.TechIdField = value;
                    this.RaisePropertyChanged("TechId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Enterprise.TechnicianBioGeneration.IGenerateTechBios")]
    public interface IGenerateTechBios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateTechBios/RenderBadge", ReplyAction="http://tempuri.org/IGenerateTechBios/RenderBadgeResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBadge(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateTechBios/RenderBio", ReplyAction="http://tempuri.org/IGenerateTechBios/RenderBioResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBio(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateTechBios/RenderBioHtml", ReplyAction="http://tempuri.org/IGenerateTechBios/RenderBioHtmlResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioHtml(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateTechBios/RenderBioCustom", ReplyAction="http://tempuri.org/IGenerateTechBios/RenderBioCustomResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioCustom(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio, string templatePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenerateTechBios/RenderBioHtmlCustom", ReplyAction="http://tempuri.org/IGenerateTechBios/RenderBioHtmlCustomResponse")]
        SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioHtmlCustom(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio, string templatePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenerateTechBiosChannel : SiteBlue.Business.Enterprise.TechnicianBioGeneration.IGenerateTechBios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenerateTechBiosClient : System.ServiceModel.ClientBase<SiteBlue.Business.Enterprise.TechnicianBioGeneration.IGenerateTechBios>, SiteBlue.Business.Enterprise.TechnicianBioGeneration.IGenerateTechBios {
        
        public GenerateTechBiosClient() {
        }
        
        public GenerateTechBiosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenerateTechBiosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateTechBiosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenerateTechBiosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBadge(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio) {
            return base.Channel.RenderBadge(bio);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBio(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio) {
            return base.Channel.RenderBio(bio);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioHtml(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio) {
            return base.Channel.RenderBioHtml(bio);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioCustom(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio, string templatePath) {
            return base.Channel.RenderBioCustom(bio, templatePath);
        }
        
        public SiteBlue.Core.Enterprise.DocumentGeneration.RenderResult RenderBioHtmlCustom(SiteBlue.Business.Enterprise.TechnicianBioGeneration.Bio bio, string templatePath) {
            return base.Channel.RenderBioHtmlCustom(bio, templatePath);
        }
    }
}
